### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by Pikku-a** [Syndace/slixmpp-omemo#3]
I'm trying to make a bot using silxmpp-omemo. I used the echo bot example as a base and edited it.

However, I get an error and I don't know how to fix it. Here is part of the log:
```

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-14' coro=<XEP_0384.get_session_manager() done, defined at /home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/slixmpp_omemo/xep_0384.py:677> exception=DeviceListDownloadFailed('Device list download failed for [botusername] under namespace eu.siacs.conversations.axolotl: Unexpected number of items retrieved: 187.')>
Traceback (most recent call last):
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/omemo/session_manager.py", line 354, in create
    self.__own_device_id = (await self.__storage.load_primitive("/own_device_id", int)).from_just()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/omemo/storage.py", line 119, in from_just
    raise NothingException("Maybe.fromJust: Nothing")  # -- yuck
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
omemo.storage.NothingException: Maybe.fromJust: Nothing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/slixmpp_omemo/xep_0384.py", line 695, in get_session_manager
    session_manager = await self.__session_manager_task
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/slixmpp_omemo/xep_0384.py", line 502, in _prepare
    session_manager = await _make_session_manager(xmpp, xep_0384).create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/omemo/session_manager.py", line 361, in create
    device_ids = cast(FrozenSet[int], frozenset()).union(*[
                                                          ^
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/omemo/session_manager.py", line 362, in <listcomp>
    frozenset((await self._download_device_list(backend.namespace, self.__own_bare_jid)).keys())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[username]/Asiakirjat/projektit/bot-temp/xmpp-ai-bot/venv/lib/python3.11/site-packages/slixmpp_omemo/xep_0384.py", line 387, in _download_device_list
    raise DeviceListDownloadFailed(
omemo.session_manager.DeviceListDownloadFailed: Device list download failed for [botusername] under namespace eu.siacs.conversations.axolotl: Unexpected number of items retrieved: 187.
```

Also, I hope you can improve the documentation. :)

**Comment by Syndace** [comment]
Please try v1.2.2, it might fix your issue

**Comment by Pikku-a** [comment]
Updating fixed it. 👍

By the way, when I try sending a message to the bot using Dino, I get "Unencrypted message or unsupported message encryption". But with Gajim it seems to work. What could be the reason for this?

**Comment by Syndace** [comment]
> Updating fixed it. 👍

Great!

> By the way, when I try sending a message to the bot using Dino, I get "Unencrypted message or unsupported message encryption". But with Gajim it seems to work. What could be the reason for this?

I don't know, works fine for me with Dino. Let me know if you find steps to reproduce it consistently.
