### ISSUE TITLE
Example: Pass Jabber ID or bare Jabber ID to `class StorageImpl(Storage):`

### ISSUE THREAD

**Issue by sjehuda** [Syndace/slixmpp-omemo#4]
For the example file, I think, that it would be beneficial to pass Jabber ID or bare Jabber ID to `class StorageImpl(Storage):` and name the filename as `jabber@id.address-omemo-echo-client.json`

`JSON_FILE = f"/home/syndace/{jid_bare}-omemo-echo-client.json"`

This would prevent errors when utilizing a bot if Jabber ID is replaced.

```
future: <Task finished name='Task-19' coro=<XEP_0384.get_session_manager() done, defined at /home/admin/.venv/lib/python3.12/site-packages/slixmpp_omemo/xep_0384.py:648> exception=RuntimeError('coroutine raised StopIteration')>
Traceback (most recent call last):
  File "/home/admin/.venv/lib/python3.12/site-packages/omemo/session_manager.py", line 1492, in get_own_device_information
    return next(iter(all_own_devices - other_own_devices)), other_own_devices
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/.venv/lib/python3.12/site-packages/slixmpp_omemo/xep_0384.py", line 666, in get_session_manager
    session_manager = await self.__session_manager_task
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.venv/lib/python3.12/site-packages/slixmpp_omemo/xep_0384.py", line 479, in _prepare
    session_manager = await _make_session_manager(xmpp, xep_0384).create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.venv/lib/python3.12/site-packages/omemo/session_manager.py", line 432, in create
    device, _ = await self.get_own_device_information()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration
ERROR    Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/home/admin/.venv/lib/python3.12/site-packages/omemo/session_manager.py", line 1492, in get_own_device_information
    return next(iter(all_own_devices - other_own_devices)), other_own_devices
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

```

**Comment by Syndace** [comment]
Thanks for you suggestion, I agree that would be nice. The problem is that JIDs are not always path/file-name safe, so it's not that simple.

**Comment by Syndace** [comment]
If you want we can add a comment to the example that warns you that one state per JID is needed. I don't think adding code to encode a JID in a path-safe manner and storing state per-JID is appropriate for the little echo client example.

**Comment by sjehuda** [comment]
> If you want we can add a comment to the example that warns you that
> one state per JID is needed. I don't think adding code to encode a
> JID in a path-safe manner and storing state per-JID is appropriate
> for the little echo client example.
> 

Yes. I suppose that it would be good.

I am interested at it, because my bot is designed to handle many
contacts,, and I would rather have OMEMO keys stored upon files per
contact.

**Comment by Syndace** [comment]
Hey, I have updated the example to make the path configurable and also added a warning that you have to use a different path for each account. I hope that clears up any confusion.

If you need to convert a JID to a path-safe format, you can use something like this:

```Python
import base64
import hashlib

def encode_jid_for_path(bare_jid: str) -> str:
    """Encode a bare JID in a way that makes it safe to use in filesystem paths"""
    
    # Encode the bare JID to bytes using UTF-8
    bare_jid_bytes = bare_jid.encode("utf-8")

    # JIDs can be long. Using the hash of the JID ensures that its length does not violate file system length
    # restrictions.
    bare_jid_hash = hashlib.sha256(bare_jid_bytes).digest()

    # Encode the hash to urlsafe base64
    return base64.urlsafe_b64encode(bare_jid_hash).decode("ASCII")
```
